#! /bin/bash

case $1 in
build) docker-compose build ;;
up) docker-compose up -d ;;
down) docker-compose down ;;
restart) docker-compose down && docker-compose up -d ;;
logs) docker-compose logs -f ;;
exec) docker-compose exec lohl-finance-ui /bin/bash ;;
*) echo "Comando não encontrado" ;;
esac